//// States

// APP
export const GET_MENU_REQUESTING = 'App/GET_MENU_REQUESTING';
export const GET_MENU_SAGA_REQUESTING = 'App/GET_MENU_SAGA_REQUESTING';
export const GET_MENU_SUCCESS = 'App/GET_MENU_SUCCESS';
export const GET_MENU_ERROR = 'App/GET_MENU_ERROR';

export const GET_USER_DETAILS_REQUESTING = 'App/GET_USER_DETAILS_REQUESTING';
export const GET_USER_DETAILS_SAGA_REQUESTING = 'App/GET_USER_DETAILS_SAGA_REQUESTING';
export const GET_USER_DETAILS_SUCCESS = 'App/GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'App/GET_USER_DETAILS_ERROR';

export const SET_AUTH_DATA = 'App/SET_AUTH_DATA';

//
export const GET_CONFIG_REQUESTING = 'App/GET_CONFIG_REQUESTING';
export const GET_CONFIG_SAGA_REQUESTING = 'App/GET_CONFIG_SAGA_REQUESTING';
export const GET_CONFIG_SUCCESS = 'App/GET_CONFIG_SUCCESS';
export const GET_CONFIG_ERROR = 'App/GET_CONFIG_ERROR';
